### ISSUE TITLE
Assignment-1 Factorial 

### ISSUE THREAD

**Issue by 48bit23** [vtcbca/basic-programming-47bit23#3]
What is a factorial, and how is it defined?

**Comment by 48bit23** [comment]
A factorial is a mathematical operation that involves multiplying a number by all of the positive integers less than it. The factorial of a number is typically denoted by an exclamation mark ! following the number.

**Comment by 48bit23** [comment]
What happens if the user enters a negative number?

**Comment by 48bit23** [comment]
When the user enters a negative number in a factorial calculation, it is important to recognize that factorials are not defined for negative numbers. The factorial function is only valid for non-negative integers (0,1,2,3,…).

**Comment by 47bit23** [comment]
A factorial is a mathematical operation that involves multiplying a number by all of the positive integers less than it. The factorial of a number is typically denoted by an exclamation mark ! following the number.

**Comment by 48bit23** [comment]
What happens if the user enters a negative number?

**Comment by 47bit23** [comment]
When the user enters a negative number in a factorial calculation, it is important to recognize that factorials are not defined for negative numbers. The factorial function is only valid for non-negative integers (0,1,2,3,…).

**Comment by 48bit23** [comment]
What are some real-world applications or algorithms that use factorials?

**Comment by 47bit23** [comment]
Factorials play a significant role in many real-world applications, especially in fields like combinatorics, probability theory, computer science, and mathematics.

**Comment by 48bit23** [comment]
Thanks for helping me out !!

**Comment by 47bit23** [comment]
It's ok no problem.
