### ISSUE TITLE
Assignment - 5: Palindrome Checker

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-47bit23#4]
What is a palindrome?

**Comment by 47bit23** [comment]
A palindrome is a word, phrase, or number that reads the same backward as forward

**Comment by 51bit23** [comment]
Can You tell me a example of it ?

**Comment by 47bit23** [comment]
sure here are some example of this like "madam" or "121".

**Comment by 51bit23** [comment]
What data type is used for checking palindromes in Python?

**Comment by 47bit23** [comment]
The str data type is used for strings, and int can be converted to a string for numbers.

**Comment by 51bit23** [comment]
Can spaces and punctuation affect palindrome checking?

**Comment by 51bit23** [comment]
Yes, spaces and punctuation are considered in their positions unless explicitly ignored in the program.

**Comment by 47bit23** [comment]
Yes, spaces and punctuation are considered in their positions unless explicitly ignored in the program.

**Comment by 51bit23** [comment]
How do you check if a string is a palindrome in Python?

**Comment by 47bit23** [comment]
Compare the string with its reversed version:

```
if string == string[::-1]:
    print("It is a palindrome.")
```

**Comment by 51bit23** [comment]
Can numbers also be palindromes?

**Comment by 47bit23** [comment]
Yes, numbers like 121 or 12321 are palindromes if they read the same backward.

**Comment by 51bit23** [comment]
okay got it !.
